os:
  - Visual Studio 2015

build:
  verbosity: detailed

configuration:
  - Debug

branches:
  except:
    - /pr\/.+/

install:

before_build:
  - mkdir mysqlcpp
  - cd mysqlcpp
  - cmake --version
  - git clone https://github.com/mysql/mysql-connector-cpp
  - cmake .
  - devenv MYSQLCPPCONN.sln /build RelWithDebInfo
  - cpack -G ZIP --config CPackConfig.cmake -C RelWithDebInfo
